[project]
name = "ztlb"
dynamic = ["version"]
description = "Backend for ZTL Maps"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "fastapi[standard]>=0.116.1",
    "pydantic>=2.11.7",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[project.scripts]
ztlb = "ztlb.cli:cli"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.3.0",
    "pytest-mock>=3.15.0",
    "pytest-xdist>=3.8.0",
]
lint = [
    "mypy>=1.17.1",
    "pre-commit>=4.3.0",
    "ruff>=0.12.12",
]

[tool.ruff]
line-length = 130

[tool.ruff.lint]
select = [
    "E",    # pycodestyle
    "F",    # pyflakes
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",    # isort
    "D",    # pydocstyle
    "PL",   # pylint
]
ignore = [
    "D100",
    "D104",
    "D106",
    "D107",
    "PLR2004",
    "PLW0603",
    "PLR0912",
    "PLR0913",
    "PLR0915",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**/*.py" = ["E501"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "single"

[tool.pytest.ini_options]
testpaths = "tests"
filterwarnings = [
    "ignore:.*:DeprecationWarning",
    "ignore:.*:UserWarning",
    "ignore:.*:FutureWarning",
]

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
omit = [
    "__init__.py",
    "__main__.py",
]
fail_under = 90
